# Generated by Django 4.0.1 on 2022-02-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_alter_request_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
