# Generated by Django 4.0.1 on 2022-02-09 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quickstart', '0005_alter_request_createdby'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('uid', models.UUIDField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(blank=True, max_length=5000, null=True)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.request')),
            ],
        ),
    ]
