# Generated by Django 4.0.1 on 2022-02-17 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0010_alter_userextensions_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='createdBy',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', related_query_name='log', to='quickstart.request'),
        ),
    ]
