# Generated by Django 4.0.1 on 2022-02-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0011_alter_requestlog_createdby_alter_requestlog_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='project',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='request',
            name='data',
            field=models.JSONField(),
        ),
    ]
