# Generated by Django 4.0.1 on 2022-02-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0013_alter_request_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
